[package]
name = "custom_map_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
create_vox = "1.0.1"
color-reduction = "0.1.2"